//import './globals.css'
'use client'
import { Inter } from 'next/font/google';
import 'bootstrap/dist/css/bootstrap.min.css';
import Container from 'react-bootstrap/Container';
import Nav from 'react-bootstrap/Nav';
import Navbar from 'react-bootstrap/Navbar';
import NavDropdown from 'react-bootstrap/NavDropdown';
const inter = Inter({ subsets: ['latin'] })

import style1 from "./styles/style.module.css";
import Link from 'next/link';


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

    <html lang="en">

      <body className={inter.className}>
        <Container>
          <header>
            <Navbar expand="lg" className="bg-body-tertiary">
              <Container>

                <Link className="navbar-brand" href="/">React-Bootstrap</Link>

                <Navbar.Toggle aria-controls="basic-navbar-nav" />
                <Navbar.Collapse id="basic-navbar-nav">
                  <Nav className="me-auto">
                    <Link className="nav-link" href="/facebook">Facebook</Link>
                    <Link className="nav-link" href="/youtube">YouTube</Link>
                    <Link className="nav-link" href="/tiktok">TikTok</Link>
                    <NavDropdown title="Dropdown" id="basic-nav-dropdown">
                      <NavDropdown.Item href="#action/3.1">Action</NavDropdown.Item>
                      <NavDropdown.Item href="#action/3.2">
                        Another action
                      </NavDropdown.Item>
                      <NavDropdown.Item href="#action/3.3">Something</NavDropdown.Item>
                      <NavDropdown.Divider />
                      <NavDropdown.Item href="#action/3.4">
                        Separated link
                      </NavDropdown.Item>
                    </NavDropdown>
                  </Nav>
                </Navbar.Collapse>
              </Container>
            </Navbar>


          </header>
          <main>
            {children}
          </main>
          <footer className={style1.footer}>
            <h3>Khoa hoc NextJs</h3>
          </footer>
        </Container>
      </body>
    </html>

  )
}
